### ISSUE TITLE
Our new ToDo-List

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [tmolitor-stud-tu/Monal#12]
- [ ] Fix smacks counting bugs on network connectivity change
- [ ] Fix automatic reconnect on connectivity change (even when backgrounded) This is needed to make "write while hibernated" more useful/better working
- [ ] Fix many bugs in notification handling

**Comment by tmolitor-stud-tu** [comment]
@anurodhp just for your info

**Comment by Echolon** [comment]
Do you want me transfer this into issues in the official Monal repo?
